### PR TITLE
Account lockout functionality

### PR DESCRIPTION
**Pull request by bryan-robitaille**
As specified in the vulnerability report this PR is to address the brute force vulnerability identified.

**How it works**

1.  When someone tries to login, we first check to see if they are currently blocked. We check the username they are trying to use, as well as the IP address. If they are blocked, goto step 5. If not blocked go to step 2.

2.  They are not blocked, so we check to see if the login was valid. If valid go to step 6. If not valid go to step 3.

3.  Login attempt wasn't valid. Add their username and IP address for this attempt to the cache. If this brings them over the limit, add them to the blocked list, and then goto step 5. If not over the limit goto step 4.

4.  login was invalid, but not over the limit. Send them back to the login screen to try again.

5.  User is blocked: Send them to the blocked page, telling them they are blocked, and give an estimate on when they will be unblocked.

6.  Login is valid. Reset any failed login attempts, and forward to their destination.

The solution leverages the package django-defender and redis alpine image for cache.  The lockout template can use some UX review and changes to language as required.  The settings are currently set in the config.py file however should be moved to the Django admin interface.

**Discussion Needed On**
1.  Should be include the movement of the defender setting to the django admin interface in this PR
2.  UX / Layout of locked_out.html template when informing users their account has been locked.
Will add screen shot of template tomorrow

### CODE REVIEW

**Comment by piet0024** [comment]
Leaving some thoughts on the experience and UI for discussion.

-  Should we send an email to the user when their account has been locked? The email could give more information about the lockout, how to contact helpdesk or how to recover the account. It could also inform users of others trying to get into their account.
- After a certain number of incorrect attempts, just before the lockout, could the error message contain links to recover password? I'm not sure if there is a potential security risk with that. We can just let them wait a short amount of time (10mins seems reasonable).
- Do we want to give users the option of password recovery while their account is locked? We may get a flood of help desk requests asking to be unlocked.
- If the site customisation does not have a help desk link (others using generic account) what steps do users take to unlock their account?

I'll take a look at the UI in a bit and add more feedback. Again just adding thoughts for discussion.

**Comment by Steph4104** [comment]
@bryan-robitaille , can you take a look at my change. I know it's working fine on a manuelle installation but I can't test on docker.

**Comment by bryan-robitaille** [comment]
@Steph4104 I ran it in Docker and everything works.  Just have that question above regarding the Disabling IP Lockout.
Also noticed that you copied over the majority of the functions from the defender library into application pleio_acount/utils.py.  Was this because the stock library functions could not be used and required modification?

**Comment by brucetbarrett** [comment]
@bryan-robitaille - in steps 3-4 are you comparing both the username and the IP address? NOTE: corporate users behind a firewall are typically NATed to they all appear to have the same IP address.

We should specify a time frame for step 5. Although not specifically defined in ITSG-33, the minimum lockout duration should be 15 minutes.

**Comment by bryan-robitaille** [comment]
Reminder to myself - Refactor code to either only over ride required functions from defender package or update defender package with enhanced functionality and submit pull request to upstream.

**Comment by bryan-robitaille** [comment]
This pull request is superceded by #106

**Pull request closed without merging**
